FROM scratch

MAINTAINER leosun <leosunsl@outlook.com>

COPY qemu-aarch64-static /usr/bin/

RUN wget https://github.com/breakersun/lede/releases/download/test/openwrt-armvirt-64-default-rootfs.tar.gz

ADD openwrt-armvirt-64-default-rootfs.tar.gz /

USER root

# using exec format so that /sbin/init is proc 1 (see procd docs)
CMD ["/sbin/init"]
