FROM scratch

MAINTAINER leosun <leosunsl@outlook.com>

COPY qemu-aarch64-static /usr/bin/

ADD openwrt-armvirt-64-default-rootfs.tar.gz /

ADD luci-app-ssr-plus_1-115_all.ipk /tmp/luci-app-ssr-plus_1-115_all.ipk

RUN mkdir /var/lock && \
	opkg install /tmp/luci-app-ssr-plus_1-115_all.ipk

USER root

# using exec format so that /sbin/init is proc 1 (see procd docs)
CMD ["/sbin/init"]
