#!/bin/bash

BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)

if [ "${BUILD_ARCH}" == "Dockerfile" ] || [ -z "${DOCKERFILE_PATH}" ]; then
  echo 'qemu-user-static: Download not required for current arch'
  exit 0
fi

docker run --rm --privileged multiarch/qemu-user-static:register --reset
